### ISSUE TITLE
Include Zenodo citations

### ISSUE THREAD

**Issue by sarthakpati** [BrainLesion/eReg#19]
**Is your feature request related to a problem? Please describe.**
Create separate DOIs automatically using Zenodo.

**Describe the solution you'd like**
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Describe alternatives you've considered**
N.A.

**Additional context**
The org admin needs to enable [3rd party access to Zenodo](https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization).

**Comment by neuronflow** [comment]
<img width="1354" alt="Screenshot 2023-12-14 at 16 39 18" src="https://github.com/BrainLesion/eReg/assets/7048826/068b6f1a-1ac2-4453-adb9-a111e8fdae01">
good?

**Comment by neuronflow** [comment]
done
